plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
title: Muhamad Haidar Khan
description: Thank You For Visiting! :)
avatar: https://avatars.githubusercontent.com/u/159702853?v=4
subscribe: false
location: Lahore, Punjab, Pakistan
author: Muhamad Haidar Khan
skin: midnight
social:
  name: Muhamad Haidar Khan
  links:
    - https://linkedin.com/in/haidarkhan
